### PR TITLE
Unavailable Albums feature

### PR DESCRIPTION
**Pull request by nikrowell**
Hi Matt

Thanks for the great Chrome Extension! One thing that annoys me most about Rdio is how albums I've added to my favorites occasionally become **Unavailable**, but are often still available somewhere under a slightly different name. 

I've added a new feature to the Favorites page, under the view toggle menu component. There is now an additional item in that menu that shows an "Unavailable Albums" dialog so it's easy to monitor what albums in your collection are out of date. 

Cheers!

### CODE REVIEW

**Comment by matt-h** [comment]
Awesome, thanks for the new feature. It looks good. I'm merging it in.

**Comment by jabalong** [comment]
"I've added a new feature to the Favorites page, under the view toggle menu component."

I don't follow. Where is this new feature?

Am on the Favorites page, but not sure what's meant by the view toggle.

The Overview menu still says "Overview" and "Albums & Songs".

I have updated to version 2.9. Cheers.

**Comment by nikrowell** [comment]
@jabalong it's under the sort by menu on the right ... wasn't sure what to call that, but **sort menu** probably makes more sense. 

screen shot 2015-08-25 at 6 21 12 am

**Comment by jabalong** [comment]
Ah, thanks. Hadn't seen it because I was viewing under Overview (where that menu greyed out), so had to first switch to Albums & Songs.

**Pull request merged**
